import React from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import './Terms.css';

const Privacy = () => {
  return (
    <div className="terms-page">
      <Navbar />

      <section className="terms-hero">
        <div className="container">
          <h1 className="terms-hero-title">
            <span className="brand-highlight">RentUFS</span> Privacy Policy
          </h1>
          <p className="terms-hero-subtitle">Updated May 12, 2026</p>
        </div>
      </section>

      <section className="terms-content">
        <div className="container">
          <div className="terms-toc">
            <h2>Table of Contents</h2>
            <ol>
              <li><a href="#section-1">Introduction</a></li>
              <li><a href="#section-2">Information We Collect</a></li>
              <li><a href="#section-3">How We Use Your Information</a></li>
              <li><a href="#section-4">How We Share Your Information</a></li>
              <li><a href="#section-5">Third-Party Service Providers</a></li>
              <li><a href="#section-6">Cookies and Tracking Technologies</a></li>
              <li><a href="#section-7">Data Retention</a></li>
              <li><a href="#section-8">Data Security</a></li>
              <li><a href="#section-9">Your Privacy Rights</a></li>
              <li><a href="#section-10">Children&rsquo;s Privacy</a></li>
              <li><a href="#section-11">International Users</a></li>
              <li><a href="#section-12">Changes to This Policy</a></li>
              <li><a href="#section-13">Contact Us</a></li>
            </ol>
          </div>

          <article id="section-1" className="terms-section">
            <h2>1. Introduction</h2>
            <p>
              RentUFS (&ldquo;RentUFS,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) operates a
              peer-to-peer car rental marketplace that connects vehicle owners
              (&ldquo;hosts&rdquo;) with renters (&ldquo;drivers&rdquo;). This Privacy Policy explains
              how we collect, use, share, and protect personal information when
              you access or use our website, mobile applications, and related
              services (collectively, the &ldquo;Services&rdquo;).
            </p>
            <p>
              By using our Services, you acknowledge that you have read and
              understood this Privacy Policy. This Policy is incorporated into
              and forms part of our Terms of Service.
            </p>
          </article>

          <article id="section-2" className="terms-section">
            <h2>2. Information We Collect</h2>
            <p>
              We collect information you provide directly to us, information
              generated by your use of the Services, and information from third
              parties.
            </p>

            <p><strong>Information you provide directly.</strong></p>
            <ul className="terms-list">
              <li><strong>Account information:</strong> name, email address, phone number, password, date of birth, and account type (driver, host, or both).</li>
              <li><strong>Identity verification:</strong> driver&rsquo;s license number, issuing state, expiration date, and uploaded license images.</li>
              <li><strong>Host information:</strong> business name, business address, tax identification information for payouts, and bank account or payout details handled through our payment processor.</li>
              <li><strong>Vehicle information:</strong> VIN, license plate, make, model, year, photos, pricing, location, and registration documents.</li>
              <li><strong>Booking information:</strong> rental dates, pickup and return inspections, communications between hosts and drivers, and incident reports.</li>
              <li><strong>Payment information:</strong> we do not store full credit card numbers; payments are processed by Stripe and we retain only tokenized references and last-4 digits.</li>
              <li><strong>Communications:</strong> messages you send to us via email, SMS, in-app chat, or support requests.</li>
            </ul>

            <p><strong>Information collected automatically.</strong></p>
            <ul className="terms-list">
              <li><strong>Usage data:</strong> pages viewed, features used, search queries, timestamps, and referring URLs.</li>
              <li><strong>Device and log data:</strong> IP address, browser type, operating system, device identifiers, and crash logs.</li>
              <li><strong>Location data:</strong> approximate location derived from IP address, and (where you provide consent) precise location used for nearby vehicle search and pickup/return verification.</li>
              <li><strong>Cookies and similar technologies:</strong> see Section 6.</li>
            </ul>

            <p><strong>Information from third parties.</strong></p>
            <ul className="terms-list">
              <li>Authentication providers (e.g., Sign in with Google) for sign-in flows.</li>
              <li>Payment processors for transaction status and dispute information.</li>
              <li>Insurance partners for coverage eligibility, on-rent coverage activation, and claim status.</li>
              <li>Mapping and geocoding providers used to display vehicle locations.</li>
              <li>Identity and driving record verification services where required by law or our risk policies.</li>
            </ul>
          </article>

          <article id="section-3" className="terms-section">
            <h2>3. How We Use Your Information</h2>
            <p>We use the information we collect to:</p>
            <ul className="terms-list">
              <li>Provide, maintain, and improve the Services, including matching renters with hosts, processing bookings, and supporting trips end-to-end.</li>
              <li>Process payments, payouts, refunds, and incidental charges such as tolls, citations, and host-submitted charges.</li>
              <li>Verify identity, eligibility, and driver licensing.</li>
              <li>Bind, activate, and manage on-rent insurance coverage with our insurance partners.</li>
              <li>Communicate with you about your account, bookings, support inquiries, security alerts, and policy updates via email and SMS.</li>
              <li>Detect, prevent, and respond to fraud, abuse, security incidents, and violations of our Terms of Service.</li>
              <li>Comply with legal obligations, court orders, and lawful requests from public authorities.</li>
              <li>Analyze usage patterns to understand how the Services are used and to improve features and reliability.</li>
            </ul>
          </article>

          <article id="section-4" className="terms-section">
            <h2>4. How We Share Your Information</h2>
            <p>
              We do not sell your personal information. We share personal
              information only as described below:
            </p>
            <ul className="terms-list">
              <li><strong>Between hosts and drivers:</strong> when you book a vehicle or accept a booking, we share the information reasonably necessary for the trip, including name, profile photo, phone number, pickup and return times, and inspection records.</li>
              <li><strong>Service providers:</strong> payment processors, SMS and email gateways, mapping providers, cloud hosting providers, insurance partners, toll-management partners, and analytics providers, each acting on our behalf and bound by contractual confidentiality obligations.</li>
              <li><strong>Insurance and claims:</strong> in the event of an incident, claim, or loss, we may share information with our insurance partners, brokers, and adjusters as necessary to investigate and resolve the matter.</li>
              <li><strong>Law enforcement and legal process:</strong> when required by subpoena, court order, or other valid legal process, or where we believe in good faith that disclosure is necessary to protect rights, safety, or property.</li>
              <li><strong>Business transfers:</strong> in connection with a merger, acquisition, financing, or sale of assets, subject to standard confidentiality protections.</li>
              <li><strong>With your consent:</strong> in any other case where you have directed us to share information.</li>
            </ul>
          </article>

          <article id="section-5" className="terms-section">
            <h2>5. Third-Party Service Providers</h2>
            <p>
              The Services rely on third-party providers, each of which receives
              only the information necessary to perform its function. These
              currently include:
            </p>
            <ul className="terms-list">
              <li><strong>Stripe</strong> for payment processing and payouts.</li>
              <li><strong>Twilio</strong> for transactional SMS notifications.</li>
              <li><strong>SendGrid</strong> for transactional email delivery.</li>
              <li><strong>Google Maps Platform</strong> for geocoding, location search, and map display.</li>
              <li><strong>MongoDB Atlas</strong> for database hosting.</li>
              <li><strong>Cloudinary</strong> for image hosting and delivery.</li>
              <li><strong>TeqMobility</strong> for on-rent insurance coverage.</li>
              <li><strong>TollSpot</strong> for automated toll detection and settlement.</li>
            </ul>
            <p>
              Each of these providers operates under its own privacy policy. We
              encourage you to review their policies for additional detail on
              how they handle your information.
            </p>
          </article>

          <article id="section-6" className="terms-section">
            <h2>6. Cookies and Tracking Technologies</h2>
            <p>
              We use cookies, local storage, and similar technologies to keep
              you signed in, remember preferences, secure your session, and
              analyze how the Services are used. You can control cookies through
              your browser settings; disabling cookies may affect your ability
              to use parts of the Services, such as staying signed in between
              visits.
            </p>
          </article>

          <article id="section-7" className="terms-section">
            <h2>7. Data Retention</h2>
            <p>
              We retain personal information for as long as your account is
              active and as needed to provide the Services. We may retain
              certain information for longer where required to comply with
              legal, tax, accounting, insurance, dispute resolution, or fraud
              prevention obligations. Booking records and related communications
              are typically retained for at least the period required by
              applicable law and any active or potential insurance claim
              periods.
            </p>
          </article>

          <article id="section-8" className="terms-section">
            <h2>8. Data Security</h2>
            <p>
              We use commercially reasonable administrative, technical, and
              physical safeguards to protect personal information, including
              encryption in transit, hashed passwords, scoped access controls,
              and secure handling of payment data through PCI-compliant
              processors. No system is perfectly secure, however, and we cannot
              guarantee the absolute security of your information.
            </p>
          </article>

          <article id="section-9" className="terms-section">
            <h2>9. Your Privacy Rights</h2>
            <p>
              Depending on where you live, you may have the right to:
            </p>
            <ul className="terms-list">
              <li><strong>Access</strong> the personal information we hold about you.</li>
              <li><strong>Correct</strong> inaccurate or incomplete information.</li>
              <li><strong>Delete</strong> your account and associated personal information, subject to records we must retain for legal, tax, or insurance reasons.</li>
              <li><strong>Object to or restrict</strong> certain processing.</li>
              <li><strong>Port</strong> your information to another service in a structured, machine-readable format.</li>
              <li><strong>Opt out</strong> of SMS messages at any time by replying STOP to any text from RentUFS.</li>
              <li><strong>Withdraw consent</strong> for any processing based on consent, without affecting the lawfulness of processing before withdrawal.</li>
            </ul>
            <p>
              To exercise any of these rights, contact us at{' '}
              <strong>support@rentufs.com</strong>. We will respond within the
              time period required by applicable law.
            </p>
            <p>
              <strong>California residents</strong> may have additional rights
              under the California Consumer Privacy Act (CCPA), including the
              right to know what categories of personal information we collect,
              the right to request deletion, and the right not to be
              discriminated against for exercising these rights. We do not sell
              personal information.
            </p>
          </article>

          <article id="section-10" className="terms-section">
            <h2>10. Children&rsquo;s Privacy</h2>
            <p>
              The Services are not directed to individuals under 21 years of
              age, and we do not knowingly collect personal information from
              individuals under 21. If you believe a person under 21 has
              provided us with personal information, please contact us at{' '}
              <strong>support@rentufs.com</strong> and we will take appropriate
              steps to delete it.
            </p>
          </article>

          <article id="section-11" className="terms-section">
            <h2>11. International Users</h2>
            <p>
              The Services are hosted in the United States. If you access the
              Services from outside the United States, your information will be
              transferred to and processed in the United States, which may have
              data protection laws different from those of your country.
            </p>
          </article>

          <article id="section-12" className="terms-section">
            <h2>12. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. When we do,
              we will revise the &ldquo;Updated&rdquo; date at the top of this page and,
              where appropriate, notify you by email or in-app notice. Your
              continued use of the Services after a revised Policy becomes
              effective constitutes acceptance of the updated Policy.
            </p>
          </article>

          <article id="section-13" className="terms-section">
            <h2>13. Contact Us</h2>
            <p>
              If you have questions about this Privacy Policy or our privacy
              practices, contact us at:
            </p>
            <p>
              <strong>support@rentufs.com</strong>
            </p>
          </article>

          <p className="terms-footnote">
            For questions about this Privacy Policy, contact us at{' '}
            <strong>support@rentufs.com</strong>.
          </p>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default Privacy;
